---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - shelly.thirdimpact.io
  resources:
  - shellydevices
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shelly.thirdimpact.io
  resources:
  - shellydevices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shelly.thirdimpact.io
  resources:
  - shellyprofiles
  verbs:
  - get
  - list
  - watch
