//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSection) DeepCopyInto(out *AuthSection) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSection.
func (in *AuthSection) DeepCopy() *AuthSection {
	if in == nil {
		return nil
	}
	out := new(AuthSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BLESection) DeepCopyInto(out *BLESection) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BLESection.
func (in *BLESection) DeepCopy() *BLESection {
	if in == nil {
		return nil
	}
	out := new(BLESection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudSection) DeepCopyInto(out *CloudSection) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudSection.
func (in *CloudSection) DeepCopy() *CloudSection {
	if in == nil {
		return nil
	}
	out := new(CloudSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareSection) DeepCopyInto(out *FirmwareSection) {
	*out = *in
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareSection.
func (in *FirmwareSection) DeepCopy() *FirmwareSection {
	if in == nil {
		return nil
	}
	out := new(FirmwareSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSection) DeepCopyInto(out *MQTTSection) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSection.
func (in *MQTTSection) DeepCopy() *MQTTSection {
	if in == nil {
		return nil
	}
	out := new(MQTTSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameSection) DeepCopyInto(out *NameSection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameSection.
func (in *NameSection) DeepCopy() *NameSection {
	if in == nil {
		return nil
	}
	out := new(NameSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NightMode) DeepCopyInto(out *NightMode) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Brightness != nil {
		in, out := &in.Brightness, &out.Brightness
		*out = new(int32)
		**out = **in
	}
	if in.ActiveBetween != nil {
		in, out := &in.ActiveBetween, &out.ActiveBetween
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NightMode.
func (in *NightMode) DeepCopy() *NightMode {
	if in == nil {
		return nil
	}
	out := new(NightMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileConfig) DeepCopyInto(out *ProfileConfig) {
	*out = *in
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(SystemSection)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(NameSection)
		**out = **in
	}
	if in.MQTT != nil {
		in, out := &in.MQTT, &out.MQTT
		*out = new(MQTTSection)
		(*in).DeepCopyInto(*out)
	}
	if in.Cloud != nil {
		in, out := &in.Cloud, &out.Cloud
		*out = new(CloudSection)
		(*in).DeepCopyInto(*out)
	}
	if in.BLE != nil {
		in, out := &in.BLE, &out.BLE
		*out = new(BLESection)
		(*in).DeepCopyInto(*out)
	}
	if in.WS != nil {
		in, out := &in.WS, &out.WS
		*out = new(WSSection)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthSection)
		(*in).DeepCopyInto(*out)
	}
	if in.Switch != nil {
		in, out := &in.Switch, &out.Switch
		*out = new(SwitchSection)
		(*in).DeepCopyInto(*out)
	}
	if in.Wifi != nil {
		in, out := &in.Wifi, &out.Wifi
		*out = new(WifiSection)
		(*in).DeepCopyInto(*out)
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(FirmwareSection)
		(*in).DeepCopyInto(*out)
	}
	if in.Schedules != nil {
		in, out := &in.Schedules, &out.Schedules
		*out = new(ScheduleSection)
		(*in).DeepCopyInto(*out)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(UISection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileConfig.
func (in *ProfileConfig) DeepCopy() *ProfileConfig {
	if in == nil {
		return nil
	}
	out := new(ProfileConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleCallSpec) DeepCopyInto(out *ScheduleCallSpec) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleCallSpec.
func (in *ScheduleCallSpec) DeepCopy() *ScheduleCallSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduleCallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleJobSpec) DeepCopyInto(out *ScheduleJobSpec) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Calls != nil {
		in, out := &in.Calls, &out.Calls
		*out = make([]ScheduleCallSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleJobSpec.
func (in *ScheduleJobSpec) DeepCopy() *ScheduleJobSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduleJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleSection) DeepCopyInto(out *ScheduleSection) {
	*out = *in
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]ScheduleJobSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleSection.
func (in *ScheduleSection) DeepCopy() *ScheduleSection {
	if in == nil {
		return nil
	}
	out := new(ScheduleSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellyDevice) DeepCopyInto(out *ShellyDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellyDevice.
func (in *ShellyDevice) DeepCopy() *ShellyDevice {
	if in == nil {
		return nil
	}
	out := new(ShellyDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShellyDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellyDeviceList) DeepCopyInto(out *ShellyDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShellyDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellyDeviceList.
func (in *ShellyDeviceList) DeepCopy() *ShellyDeviceList {
	if in == nil {
		return nil
	}
	out := new(ShellyDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShellyDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellyDeviceSpec) DeepCopyInto(out *ShellyDeviceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellyDeviceSpec.
func (in *ShellyDeviceSpec) DeepCopy() *ShellyDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(ShellyDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellyDeviceStatus) DeepCopyInto(out *ShellyDeviceStatus) {
	*out = *in
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
	if in.DriftedSections != nil {
		in, out := &in.DriftedSections, &out.DriftedSections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellyDeviceStatus.
func (in *ShellyDeviceStatus) DeepCopy() *ShellyDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(ShellyDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellyProfile) DeepCopyInto(out *ShellyProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellyProfile.
func (in *ShellyProfile) DeepCopy() *ShellyProfile {
	if in == nil {
		return nil
	}
	out := new(ShellyProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShellyProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellyProfileList) DeepCopyInto(out *ShellyProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShellyProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellyProfileList.
func (in *ShellyProfileList) DeepCopy() *ShellyProfileList {
	if in == nil {
		return nil
	}
	out := new(ShellyProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShellyProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellyProfileSpec) DeepCopyInto(out *ShellyProfileSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellyProfileSpec.
func (in *ShellyProfileSpec) DeepCopy() *ShellyProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ShellyProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchSection) DeepCopyInto(out *SwitchSection) {
	*out = *in
	if in.InitialState != nil {
		in, out := &in.InitialState, &out.InitialState
		*out = new(string)
		**out = **in
	}
	if in.AutoOn != nil {
		in, out := &in.AutoOn, &out.AutoOn
		*out = new(bool)
		**out = **in
	}
	if in.AutoOnDelay != nil {
		in, out := &in.AutoOnDelay, &out.AutoOnDelay
		*out = new(int32)
		**out = **in
	}
	if in.AutoOff != nil {
		in, out := &in.AutoOff, &out.AutoOff
		*out = new(bool)
		**out = **in
	}
	if in.AutoOffDelay != nil {
		in, out := &in.AutoOffDelay, &out.AutoOffDelay
		*out = new(int32)
		**out = **in
	}
	if in.PowerLimit != nil {
		in, out := &in.PowerLimit, &out.PowerLimit
		*out = new(int32)
		**out = **in
	}
	if in.VoltageLimit != nil {
		in, out := &in.VoltageLimit, &out.VoltageLimit
		*out = new(int32)
		**out = **in
	}
	if in.CurrentLimit != nil {
		in, out := &in.CurrentLimit, &out.CurrentLimit
		*out = new(int32)
		**out = **in
	}
	if in.AutorecoverVoltageErrors != nil {
		in, out := &in.AutorecoverVoltageErrors, &out.AutorecoverVoltageErrors
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchSection.
func (in *SwitchSection) DeepCopy() *SwitchSection {
	if in == nil {
		return nil
	}
	out := new(SwitchSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemSection) DeepCopyInto(out *SystemSection) {
	*out = *in
	if in.EcoMode != nil {
		in, out := &in.EcoMode, &out.EcoMode
		*out = new(bool)
		**out = **in
	}
	if in.Discoverable != nil {
		in, out := &in.Discoverable, &out.Discoverable
		*out = new(bool)
		**out = **in
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
	if in.Latitude != nil {
		in, out := &in.Latitude, &out.Latitude
		*out = new(string)
		**out = **in
	}
	if in.Longitude != nil {
		in, out := &in.Longitude, &out.Longitude
		*out = new(string)
		**out = **in
	}
	if in.SNTPServer != nil {
		in, out := &in.SNTPServer, &out.SNTPServer
		*out = new(string)
		**out = **in
	}
	if in.DebugLevel != nil {
		in, out := &in.DebugLevel, &out.DebugLevel
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemSection.
func (in *SystemSection) DeepCopy() *SystemSection {
	if in == nil {
		return nil
	}
	out := new(SystemSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UISection) DeepCopyInto(out *UISection) {
	*out = *in
	if in.LEDMode != nil {
		in, out := &in.LEDMode, &out.LEDMode
		*out = new(string)
		**out = **in
	}
	if in.NightMode != nil {
		in, out := &in.NightMode, &out.NightMode
		*out = new(NightMode)
		(*in).DeepCopyInto(*out)
	}
	if in.ButtonInMode != nil {
		in, out := &in.ButtonInMode, &out.ButtonInMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UISection.
func (in *UISection) DeepCopy() *UISection {
	if in == nil {
		return nil
	}
	out := new(UISection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WSSection) DeepCopyInto(out *WSSection) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WSSection.
func (in *WSSection) DeepCopy() *WSSection {
	if in == nil {
		return nil
	}
	out := new(WSSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiAP) DeepCopyInto(out *WifiAP) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.RangeExtender != nil {
		in, out := &in.RangeExtender, &out.RangeExtender
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiAP.
func (in *WifiAP) DeepCopy() *WifiAP {
	if in == nil {
		return nil
	}
	out := new(WifiAP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiNetwork) DeepCopyInto(out *WifiNetwork) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.PassSecretRef != nil {
		in, out := &in.PassSecretRef, &out.PassSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiNetwork.
func (in *WifiNetwork) DeepCopy() *WifiNetwork {
	if in == nil {
		return nil
	}
	out := new(WifiNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiRoam) DeepCopyInto(out *WifiRoam) {
	*out = *in
	if in.RSSIThreshold != nil {
		in, out := &in.RSSIThreshold, &out.RSSIThreshold
		*out = new(int32)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiRoam.
func (in *WifiRoam) DeepCopy() *WifiRoam {
	if in == nil {
		return nil
	}
	out := new(WifiRoam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiSection) DeepCopyInto(out *WifiSection) {
	*out = *in
	if in.Sta != nil {
		in, out := &in.Sta, &out.Sta
		*out = new(WifiNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.Sta1 != nil {
		in, out := &in.Sta1, &out.Sta1
		*out = new(WifiNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.AP != nil {
		in, out := &in.AP, &out.AP
		*out = new(WifiAP)
		(*in).DeepCopyInto(*out)
	}
	if in.Roam != nil {
		in, out := &in.Roam, &out.Roam
		*out = new(WifiRoam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiSection.
func (in *WifiSection) DeepCopy() *WifiSection {
	if in == nil {
		return nil
	}
	out := new(WifiSection)
	in.DeepCopyInto(out)
	return out
}
